/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projeto.estoque;

import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class TelaRelatórios extends javax.swing.JFrame {
    
    private final MaterialRepository materialRepository;
    private final org.springframework.context.ApplicationContext context;
    
    public TelaRelatórios(MaterialRepository materialRepository, org.springframework.context.ApplicationContext context) {
        this.materialRepository = materialRepository;
        this.context = context;
    }
    
    public void inicializarTela() {
        // Garante que só chama o initComponents se a tela estiver limpa
        if (this.getContentPane().getComponentCount() == 0) {
            initComponents();
        }
        setLocationRelativeTo(null);
        
        calcularGerarInsights(); // Método que vai fazer as contas
        
        // FORÇA o Java Swing a apagar o texto antigo da tela e pintar o novo calculado
    this.revalidate();
    this.repaint();
        
        setVisible(true);
    }
    
    private void calcularGerarInsights() {
        List<Material> materiais = materialRepository.findAll();
        
        double valorTotalEstoque = 0.0;
        double pesoTotalKg = 0.0;
        int totalItensFisicos = 0;
        
        // Loop para somar os dados de todos os materiais do banco
        for (Material m : materiais) {
            // Valor do item = quantidade * preco
            valorTotalEstoque += (m.getQuantidade() * m.getPreco());
            
            // Peso total = quantidade * peso unitário
            pesoTotalKg += (m.getQuantidade() * m.getPesoKg());
            
            // Soma total de unidades no estoque
            totalItensFisicos += m.getQuantidade();
        }
        
        // Convertendo o peso para Toneladas para ficar mais profissional
        double pesoTotalToneladas = pesoTotalKg / 1000.0;
        
        // Agora vamos jogar esses valores calculados nas Labels da tela
        lblValorTotal.setText(String.format("R$ %.2f", valorTotalEstoque));
        lblPesoTotal.setText(String.format("%.2f t", pesoTotalToneladas));
        lblTotalItens.setText(String.valueOf(totalItensFisicos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalItens = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Dashboard & Insights de Estoque");

        jLabel2.setText("Valor total em Estoque:");

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorTotal.setText("jLabel3");

        jLabel4.setText("Peso total armazenado:");

        lblPesoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesoTotal.setText("jLabel5");

        jLabel6.setText("Quantidade total de estoque:");

        lblTotalItens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalItens.setText("jLabel7");

        btnMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnMenu.setText("   Menu   ");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnMenu);

        jMenu2.setBackground(new java.awt.Color(51, 102, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu2.setText("   Gerenciar Estoque   ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(51, 102, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu3.setText("   Consultar Estoque   ");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 102, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu4.setText("   Sobre   ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(51, 102, 255));
        jMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu5.setText("   Sair   ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(lblTotalItens, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesoTotal)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalItens)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        // 1. Pede a instância do Menu que já está rodando no Spring
        TelaMenu menu = context.getBean(TelaMenu.class);

        // 2. Torna o menu principal visível novamente
        menu.setVisible(true); 

        // 3. Fecha a janela atual onde o usuário estava
        this.dispose();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        // 1. Pede a tela de cadastro para o Spring
        TelaCadastroMaterial cadastro = context.getBean(TelaCadastroMaterial.class);

        // 2. Abre a tela de cadastro limpa para um novo registro
        cadastro.inicializarTela(); 

        // 3. Fecha a tela de consulta atual para não acumular janelas
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        // 1. Pede para o Spring a instância correta da Tela de Consulta
        TelaConsultarEstoque consulta = context.getBean(TelaConsultarEstoque.class);

        // 2. Abre a tela de consulta (que já vai puxar os dados do banco automaticamente)
        consulta.inicializarTela();

        // 3. Esconde o menu principal para não acumular janelas abertas
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        System.exit(0); // Fecha o sistema completamente
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        // 1. Pede a instância da TelaSobre para o Spring
        TelaSobre sobre = context.getBean(TelaSobre.class);

        // 2. Abre a tela
        sobre.inicializarTela();

        // 3. Esconde o menu principal
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPesoTotal;
    private javax.swing.JLabel lblTotalItens;
    private javax.swing.JLabel lblValorTotal;
    // End of variables declaration//GEN-END:variables
}
