/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projeto.estoque;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

@Component
public class TelaConsultarEstoque extends javax.swing.JFrame {
    
    // Precisamos do repositório para buscar os materiais no banco
    private final MaterialRepository materialRepository;
    
    // Precisamos do contexto caso o usuário queira voltar para o Menu
    private final org.springframework.context.ApplicationContext context;
   
    // Construtor atualizado para o Spring Boot injetar as dependências
    public TelaConsultarEstoque(MaterialRepository materialRepository, org.springframework.context.ApplicationContext context) {
        this.materialRepository = materialRepository;
        this.context = context;
        // Não chamamos o initComponents aqui para o Spring não dar erro ao iniciar o sistema        
    }
    
    // Método principal que abre a tela e já puxa os dados do banco
    public void inicializarTela() {
        initComponents(); // Desenha a tela
        setLocationRelativeTo(null); // Centraliza no monitor
        
        preencherTabela(); // Preenche a JTable com os dados do banco H2
        
        setVisible(true); // Exibe a janela
    }
    
    // Método que vai ler o banco de dados e colocar as linhas na tabela
    private void preencherTabela() {
        // 1. Pega o modelo da tabela que você desenhou no Design
        DefaultTableModel modelo = (DefaultTableModel) tabelaMateriais.getModel();
        
        // Limpa a tabela para não duplicar dados caso reabra
        modelo.setRowCount(0); 
        
        // 2. Busca todos os materiais salvos no banco H2
        List<Material> listaMateriais = materialRepository.findAll();
        
        // 3. Coloca cada material dentro da tabela do Swing
        for (Material m : listaMateriais) {
            modelo.addRow(new Object[]{
                m.getId(),
                m.getNome(),
                m.getTipo(),
                m.getQuantidade(),
                m.getPesoKg(),
                m.getPreco()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMateriais = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaMateriais);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Consulta de Estoque");

        btnEditar.setBackground(new java.awt.Color(51, 102, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(51, 102, 255));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        jMenu1.setBackground(new java.awt.Color(51, 102, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu1.setText("   Menu   ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(51, 102, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu2.setText("   Gerenciar Estoque   ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(51, 102, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu3.setText("   Insights/Relatórios   ");
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 102, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu4.setText("   Sobre   ");
        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(51, 102, 255));
        jMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu5.setText("   Sair   ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnEditar)
                        .addGap(65, 65, 65)
                        .addComponent(btnExcluir)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaMateriais.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um material na tabela para editar.");
            return;
        }
        
        Long idMaterial = (Long) tabelaMateriais.getValueAt(linhaSelecionada, 0);
        Material materialParaEditar = materialRepository.findById(idMaterial).orElse(null);
        
        if (materialParaEditar != null) {
            TelaCadastroMaterial cadastro = context.getBean(TelaCadastroMaterial.class);

            // Passa o material que encontramos para a tela de cadastro carregar nos campos
            cadastro.prepararParaEdicao(materialParaEditar);

            this.dispose(); // Fecha a tela de consulta
        
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        // 1. Verifica qual linha o usuário selecionou
        int linhaSelecionada = tabelaMateriais.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um material na tabela para excluir.");
            return;
        }
        
        // 2. Pergunta se o usuário tem certeza (Evita exclusões por acidente)
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este material?", "Confirmar Exclusão", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            // 3. Pega o ID do material (Coluna 0 da tabela)
            Long idMaterial = (Long) tabelaMateriais.getValueAt(linhaSelecionada, 0);

            // 4. Deleta do banco H2 usando o Spring Data
            materialRepository.deleteById(idMaterial);

            // 5. Atualiza a tabela na tela para sumir com a linha apagada
            preencherTabela();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Material excluído com sucesso!");
        }                
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        System.exit(0); // Fecha o sistema completamente
        
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        // 1. Pede a tela de cadastro para o Spring
        TelaCadastroMaterial cadastro = context.getBean(TelaCadastroMaterial.class);

        // 2. Abre a tela de cadastro limpa para um novo registro
        cadastro.inicializarTela(); 

        // 3. Fecha a tela de consulta atual para não acumular janelas
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        // 1. Pede a instância do Menu que já está rodando no Spring
        TelaMenu menu = context.getBean(TelaMenu.class);

        // 2. Torna o menu principal visível novamente
        menu.setVisible(true); 

        // 3. Fecha a janela atual onde o usuário estava
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaMateriais;
    // End of variables declaration//GEN-END:variables
}
