/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projeto.estoque;

/**
 *
 * @author nanny
 */
// ESSA ANOTAÇÃO É FUNDAMENTAL PRO SPRING GERENCIAR A TELA!
@org.springframework.stereotype.Component
public class TelaLogin extends javax.swing.JFrame {
    
    private final org.springframework.context.ApplicationContext context;
    
    // Repositório que usaremos para validar o login
    private final ClienteRepository clienteRepository;
    
    // Construtor modificado para receber o repositório do Spring
    public TelaLogin(ClienteRepository clienteRepository, org.springframework.context.ApplicationContext context) {
        this.clienteRepository = clienteRepository;
        this.context = context; // Salvamos o contexto aqui
        initComponents(); // Método automático do NetBeans que desenha os componentes
        setLocationRelativeTo(null); // Centraliza a tela no meio do monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("E-mail:");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        btnEntrar.setBackground(new java.awt.Color(51, 102, 255));
        btnEntrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(txtEmail)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnEntrar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // 1. Captura o e-mail digitado e remove espaços em branco extras
        String emailDigitado = txtEmail.getText().trim();   
    
        // 2. Captura a senha de forma segura (getPassword) e converte para String
        String senhaDigitada = new String(txtSenha.getPassword());

        // Validation básica: verifica se os campos estão vazios
        if (emailDigitado.isEmpty() || senhaDigitada.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return;
        }

        // 3. Consulta o banco de dados usando o repositório do Spring Boot
        java.util.Optional<Cliente> clienteOpt = clienteRepository.findByEmail(emailDigitado);
        
        // 4. Verifica se o e-mail existe no banco e se a senha confere
        if (clienteOpt.isPresent()) {
            Cliente cliente = clienteOpt.get();
            
            if (cliente.getSenha().equals(senhaDigitada)) {
                // Se o login der certo:
                javax.swing.JOptionPane.showMessageDialog(this, "Bem-vindo, " + cliente.getNome() + "!");
                // Pegamos a TelaMenu que o Spring criou
                TelaMenu menu = context.getBean(TelaMenu.class);
                menu.inicializarTela(cliente.getNome()); // Abre o menu
                this.dispose(); // Fecha a tela de login
    
            } else {
                // Se a senha estiver errada
                javax.swing.JOptionPane.showMessageDialog(this, "Senha incorreta. Tente novamente.");
            }
        } else {
            // Se o e-mail não existir no banco de dados
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
