/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projeto.estoque;

import org.springframework.stereotype.Component;

@Component
public class TelaCadastroMaterial extends javax.swing.JFrame {
            
    // Adicione essa variável no topo, junto com o repositório:
    private final org.springframework.context.ApplicationContext context;

    // O Spring precisa desse repositório para salvar os dados no banco
    private final MaterialRepository materialRepository;

    // Construtor preparado para o Spring Boot
    public TelaCadastroMaterial(MaterialRepository materialRepository, org.springframework.context.ApplicationContext context) {
        this.materialRepository = materialRepository;
        this.context = context; // Salvamos o contexto aqui
    }
    
    // Método leve para abrir a tela
    public void inicializarTela() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private Long idMaterialEmEdicao = null; // Coloque logo abaixo das outras variáveis do topo
    
    public void prepararParaEdicao(Material m) {
        initComponents();
        setLocationRelativeTo(null);

        // Salva o ID do material que veio da tabela
        this.idMaterialEmEdicao = m.getId();

        // Preenche todos os campos de texto com os dados do material selecionado
        txtNome.setText(m.getNome());
        txtTipo.setText(m.getTipo());
        txtQuantidade.setText(String.valueOf(m.getQuantidade()));
        txtPeso.setText(String.valueOf(m.getPesoKg()));
        txtPreco.setText(String.valueOf(m.getPreco()));

        // Opcional: Mudar o texto do botão Salvar para "Atualizar" para o usuário saber que está editando
        btnSalvar.setText("Atualizar Material");

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnConsultar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Cadastro de Material");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome do Material:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Material:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Quantidade:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Peso (Kg):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Preço:");

        btnSalvar.setBackground(new java.awt.Color(51, 102, 255));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnMenu.setText("   Menu   ");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnMenu);

        btnConsultar.setBackground(new java.awt.Color(51, 102, 255));
        btnConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnConsultar.setText("Consultar Estoque");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnConsultar);

        jMenu2.setBackground(new java.awt.Color(51, 102, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu2.setText("   Insights/Relatórios   ");
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(51, 102, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu3.setText("   Sobre   ");
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 102, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jMenu4.setText("   Sair   ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(txtTipo)
                                .addComponent(jLabel2)
                                .addComponent(txtNome)
                                .addComponent(jLabel4)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0); // Fecha o sistema completamente
    }//GEN-LAST:event_jMenu4MouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Captura os dados dos campos de texto (ajuste os nomes das suas variáveis se necessário)
        String nome = txtNome.getText().trim();
        String tipo = txtTipo.getText().trim(); 
        Integer quantidade = Integer.parseInt(txtQuantidade.getText().trim());
        Double peso = Double.parseDouble(txtPeso.getText().trim());
        Double preco = Double.parseDouble(txtPreco.getText().trim());

        // Validação simples
        if (nome.isEmpty() || tipo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
            return;
        }

        // 2. Cria o objeto Material com os dados digitados
        Material novoMaterial = new Material(nome, tipo, quantidade, peso, preco);
        
        // SE estivermos editando, nós avisamos o objeto qual é o ID dele antes de salvar
        if (this.idMaterialEmEdicao != null) {
            novoMaterial.setId(this.idMaterialEmEdicao);
        }

        // 3. Salva no banco de dados usando o Spring Data!
        materialRepository.save(novoMaterial); // O Spring atualiza se tiver ID, ou cria se for nulo!

        // 4. Avisa o usuário e limpa os campos
        javax.swing.JOptionPane.showMessageDialog(this, "Material salvo com sucesso!");
        
        // SE estávamos editando, faz sentido voltar para a tela de consulta automaticamente para ver o resultado!
        if (this.idMaterialEmEdicao != null) {
            // Pede a tela de consulta para o Spring
            TelaConsultarEstoque consulta = context.getBean(TelaConsultarEstoque.class);
            // Abre ela (isso vai fazer o método preencherTabela() rodar de novo e puxar os dados atualizados!)
            consulta.inicializarTela();
            
            // Limpa a variável de edição
            this.idMaterialEmEdicao = null;
            btnSalvar.setText("Salvar");
            
            // Fecha a tela de cadastro
            this.dispose(); 
        } else {
            // Se for um cadastro novo (e você quiser continuar na tela para cadastrar mais), apenas limpa os campos:
            txtNome.setText("");
            txtTipo.setText("");
            txtQuantidade.setText("");
            txtPeso.setText("");
            txtPreco.setText("");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: Quantidade, Peso e Preço precisam ser números válidos.");
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        // 1. Pegamos a instância do Menu Principal que o Spring já criou
        TelaMenu menu = context.getBean(TelaMenu.class);
        
        // 2. Abrimos o menu novamente (como o nome do usuário já foi carregado antes, podemos apenas dar setVisible)
        menu.setVisible(true);
        
        // 3. Fechamos a tela de cadastro atual para não acumular janelas abertas
        this.dispose();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
        TelaConsultarEstoque consulta = context.getBean(TelaConsultarEstoque.class);

        // 2. Abre a tela de consulta (que já vai puxar os dados do banco automaticamente)
        consulta.inicializarTela();

        // 3. Esconde o menu principal para não acumular janelas abertas
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnConsultar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
