/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projeto.estoque;

import org.springframework.stereotype.Component;

@Component
public class TelaMenu extends javax.swing.JFrame {
    
    private final org.springframework.context.ApplicationContext context;
    
    public TelaMenu(org.springframework.context.ApplicationContext context) {
        this.context = context;
    }

    // Método para carregar o visual e mostrar a tela
    public void inicializarTela(String nomeUsuario) {
        initComponents();
        boasVindas.setText("Bem-vindo(a), " + nomeUsuario + "!");
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        boasVindas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnEstoque = new javax.swing.JMenu();
        btnInsights = new javax.swing.JMenu();
        btnSobre = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Sistema de Gestão de Estoque");

        boasVindas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boasVindas.setText("Bem-vindo(a), Usuário!");

        jLabel3.setText("Navegue pelas funcionalidades do sistema.");

        btnEstoque.setBackground(new java.awt.Color(51, 102, 255));
        btnEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnEstoque.setText("   Gerenciar Estoque  ");
        btnEstoque.setAlignmentX(1.0F);
        btnEstoque.setAlignmentY(1.0F);
        btnEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstoqueMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEstoque);

        btnInsights.setBackground(new java.awt.Color(51, 102, 255));
        btnInsights.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnInsights.setText("   Insights/Relatórios  ");
        btnInsights.setAlignmentX(1.0F);
        btnInsights.setAlignmentY(1.0F);
        btnInsights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsights.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(btnInsights);

        btnSobre.setBackground(new java.awt.Color(51, 102, 255));
        btnSobre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnSobre.setText("  Sobre  ");
        btnSobre.setAlignmentX(1.0F);
        btnSobre.setAlignmentY(1.0F);
        btnSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(btnSobre);

        btnSair.setBackground(new java.awt.Color(51, 102, 255));
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        btnSair.setText("  Sair  ");
        btnSair.setAlignmentX(1.0F);
        btnSair.setAlignmentY(1.0F);
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(this::btnSairActionPerformed);
        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(boasVindas))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(boasVindas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        System.exit(0); // Fecha o sistema completamente
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstoqueMouseClicked
        // TODO add your handling code here:
        TelaCadastroMaterial cadastro = context.getBean(TelaCadastroMaterial.class);
        cadastro.inicializarTela();
        this.dispose();
    }//GEN-LAST:event_btnEstoqueMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boasVindas;
    private javax.swing.JMenu btnEstoque;
    private javax.swing.JMenu btnInsights;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenu btnSobre;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
